package com.bezshtanko.university_admission_servlet.controller.command;

public enum CommandType {
    HOME_GET,
    LOGIN_GET,
    LOGIN_POST,
    LOGOUT_GET,
    REGISTER_GET,
    REGISTER_POST,
    ERROR_GET,

    USER_PROFILE_GET,
    USER_FACULTIES_GET,
    USER_FACULTY_GET,
    USER_FACULTY_ENROLL_GET,
    USER_FACULTY_ENROLL_POST,

    ADMIN_FACULTIES_GET,
    ADMIN_FACULTY_GET,
    ADMIN_FACULTY_NEW_GET,
    ADMIN_FACULTY_NEW_POST,
    ADMIN_FACULTY_EDIT_GET,
    ADMIN_FACULTY_EDIT_POST,
    ADMIN_FACULTY_DELETE_GET,
    ADMIN_FACULTY_ENROLLMENT_APPROVE_GET,
    ADMIN_FACULTY_FINALIZE_GET,
    ADMIN_USER_GET,
    ADMIN_USER_BLOCK_GET,
    ADMIN_USER_UNBLOCK_GET;
}
